In [1]:
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest' 
#Original Sandbox Environment: 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'5000',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': '0ad53085-1cb2-4eb8-ad9e-3ffbd7e56509',
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  #print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)

In [2]:
type(data)

dict

In [3]:
import pandas as pd

#allows the user to see all columns 
pd.set_option('display.max_columns', None)

In [4]:
# Normalising the data and organising it in a dataframe 

#A timestamp to input when the process started, and when it is currently 

df = pd.json_normalize(data['data'])
df['timestamp'] = pd.to_datetime('now')
df

C:\Users\ADMIN\Pythonnnn\lib\site-packages\pandas\core\arrays\datetimes.py:2199: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  result, tz_parsed = tslib.array_to_datetime(

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address,timestamp
0,1,Bitcoin,BTC,bitcoin,9693,2013-04-28T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.912976e+07,1.912976e+07,NaN,1,NaN,NaN,NaN,2022-08-23T17:18:00.000Z,2.145804e+04,3.262416e+10,8.7459,0.112689,0.722741,-10.008048,-5.880389,1.460078,-27.436637,4.104872e+11,39.8954,4.506188e+11,NaN,2022-08-23T17:18:00.000Z,NaN,NaN,NaN,NaN,NaN,2022-08-23 17:23:15.395766
1,1027,Ethereum,ETH,ethereum,6032,2015-08-07T00:00:00.000Z,"[mineable, pow, smart-contracts, ethereum-ecos...",NaN,1.220814e+08,1.220814e+08,NaN,2,NaN,NaN,NaN,2022-08-23T17:18:00.000Z,1.637151e+03,1.817543e+10,-1.8494,0.157698,3.656000,-12.880271,2.073542,35.513518,-16.265265,1.998656e+11,19.4288,1.998656e+11,NaN,2022-08-23T17:18:00.000Z,NaN,NaN,NaN,NaN,NaN,2022-08-23 17:23:15.395766
2,825,Tether,USDT,tether,38738,2015-02-25T00:00:00.000Z,"[payments, stablecoin, asset-backed-stablecoin...",NaN,6.754956e+10,6.915778e+10,NaN,3,NaN,NaN,NaN,2022-08-23T17:18:00.000Z,9.999809e-01,5.297807e+10,5.5100,-0.001559,-0.008511,-0.013145,-0.006255,0.065305,0.109760,6.754826e+10,6.5663,6.915646e+10,NaN,2022-08-23T17:18:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7,2022-08-23 17:23:15.395766
3,3408,USD Coin,USDC,usd-coin,5921,2018-10-08T00:00:00.000Z,"[medium-of-exchange, stablecoin, asset-backed-...",NaN,5.229369e+10,5.229369e+10,NaN,4,NaN,NaN,NaN,2022-08-23T17:18:00.000Z,9.999328e-01,5.446318e+09,0.0000,0.002853,-0.003637,-0.005098,-0.004423,-0.033740,-0.019181,5.229018e+10,5.0821,5.229018e+10,NaN,2022-08-23T17:18:00.000Z,1027.0,Ethereum,ETH,ethereum,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,2022-08-23 17:23:15.395766
4,1839,BNB,BNB,bnb,1085,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",2.000000e+08,1.613373e+08,1.613373e+08,NaN,5,NaN,NaN,NaN,2022-08-23T17:18:00.000Z,2.971655e+02,1.129878e+09,-25.1012,-0.173169,0.192982,-5.454847,12.598810,25.617009,-8.746752,4.794386e+10,4.6618,5.943310e+10,NaN,2022-08-23T17:18:00.000Z,NaN,NaN,NaN,NaN,NaN,2022-08-23 17:23:15.395766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,19744,Dot Dot Finance,DDD,dot-dot-finance,2,2022-04-25T06:44:29.000Z,[],0.000000e+00,0.000000e+00,2.339050e+07,NaN,4995,2.339050e+07,8.343528e+04,NaN,2022-08-23T17:18:00.000Z,3.567059e-03,1.155957e+04,129.9272,-0.272507,3.458623,27.643280,49.744903,16.549049,-64.806565,0.000000e+00,0.0000,8.343528e+04,NaN,2022-08-23T17:18:00.000Z,1839.0,BNB,BNB,bnb,0x84c97300a190676a19D1E13115629A11f8482Bd1,2022-08-23 17:23:15.395766
4996,10498,Saitama V1,SAITAMA,saitama-inu,31,2021-06-18T00:00:00.000Z,[],1.000000e+17,0.000000e+00,4.461151e+16,NaN,4996,4.383756e+16,3.245117e+06,NaN,2022-08-23T17:18:00.000Z,7.402594e-11,1.151562e+04,44.4362,5.757031,10.074428,-4.903006,-19.320320,0.320592,-97.916375,0.000000e+00,0.0000,7.402594e+06,NaN,2022-08-23T17:18:00.000Z,1027.0,Ethereum,ETH,ethereum,0x8b3192f5eebd8579568a2ed41e6feb402f93f73f,2022-08-23 17:23:15.395766
4997,12505,dexIRA,DEX,dexira,2,2021-10-08T09:02:07.000Z,[],1.000000e+09,0.000000e+00,1.000000e+09,NaN,4997,7.821991e+08,2.697943e+06,NaN,2022-08-23T17:18:00.000Z,3.449177e-03,1.148435e+04,70.4217,-0.477858,1.618316,0.309796,-60.895487,-36.555351,87.734392,0.000000e+00,0.0000,3.449177e+06,NaN,2022-08-23T17:18:00.000Z,1839.0,BNB,BNB,bnb,0x147e07976e1ae78287c33aafaab87760d32e50a5,2022-08-23 17:23:15.395766
4998,9490,Ara Blocks,ARA,ara-blocks,3,2021-04-29T00:00:00.000Z,"[marketplace, media]",1.000000e+09,0.000000e+00,0.000000e+00,NaN,4999,NaN,NaN,NaN,2022-08-23T17:18:00.000Z,7.647923e-04,1.144362e+04,9257.7483,0.006153,27.244891,12.127032,-4.786254,2.071133,-34.560582,0.000000e+00,0.0000,7.647923e+05,NaN,2022-08-23T17:18:00.000Z,1027.0,Ethereum,ETH,ethereum,0xa92e7c82b11d10716ab534051b271d2f6aef7df5,2022-08-23 17:23:15.395766
4999,8079,Dexfin,DXF,dexfin,10,2020-12-22T00:00:00.000Z,[],1.168000e+09,0.000000e+00,1.168000e+09,NaN,5000,NaN,NaN,NaN,2022-08-23T17:18:00.000Z,1.735233e-02,1.141965e+04,8895.8226,-3.043191,-2.937714,-9.245713,1.671203,-4.655364,-21.498075,0.000000e+00,0.0000,2.026753e+07,NaN,2022-08-23T17:18:00.000Z,1027.0,Ethereum,ETH,ethereum,0x15Eabb7500E44B7Fdb6e4051cA8DecA430cF9FB8,2022-08-23 17:23:15.395766

In [11]:
def run_api():

    global df
    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest' 
    #Original Sandbox Environment: 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
    parameters = {
      'start':'1',
      'limit':'5000',
      'convert':'USD'
    }
    headers = {
      'Accepts': 'application/json',
      'X-CMC_PRO_API_KEY': '0ad53085-1cb2-4eb8-ad9e-3ffbd7e56509',
    }

    session = Session()
    session.headers.update(headers)

    try:
      response = session.get(url, params=parameters)
      data = json.loads(response.text)
      #print(data)
    except (ConnectionError, Timeout, TooManyRedirects) as e:
      print(e)
    
    df = pd.json_normalize(data['data'])
    df['timestamp'] = pd.to_datetime('now')
    df
    
    
    if not os.path.isfile(r'C:\Users\ADMIN\Desktop\Studies, Career & VISA\Portfolio\Projects\Python\Second Project - Crypto API PullAPI.csv'):
        df.to_csv(r'C:\Users\ADMIN\Desktop\Studies, Career & VISA\Portfolio\Projects\Python\Second Project - Crypto API PullAPI.csv', header = 'column_name')
    else:
        df.to_csv(r'C:\Users\ADMIN\Desktop\Studies, Career & VISA\Portfolio\Projects\Python\Second Project - Crypto API PullAPI.csv', mode = 'a', header=False)

In [12]:
import os
from time import time
from time import sleep 


#333 stands for the max credit I can use from the API to pull data
for i in range(333):
    run_api()
    print('API Runner Completed')
    sleep(60) #sleep for 60 seconds
exit()

C:\Users\ADMIN\Pythonnnn\lib\site-packages\pandas\core\arrays\datetimes.py:2199: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  result, tz_parsed = tslib.array_to_datetime(

API Runner Completed

C:\Users\ADMIN\Pythonnnn\lib\site-packages\pandas\core\arrays\datetimes.py:2199: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  result, tz_parsed = tslib.array_to_datetime(

API Runner Completed

C:\Users\ADMIN\Pythonnnn\lib\site-packages\pandas\core\arrays\datetimes.py:2199: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  result, tz_parsed = tslib.array_to_datetime(

API Runner Completed

KeyboardInterrupt:

In [13]:
# Changed the scientific notation format to see all the numbers.

pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [14]:
# Now let's look at the coin trends over time

df3 = df.groupby('name', sort=False)[['quote.USD.percent_change_1h','quote.USD.percent_change_24h','quote.USD.percent_change_7d','quote.USD.percent_change_30d','quote.USD.percent_change_60d','quote.USD.percent_change_90d']].mean()
df3

,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d
name,,,,,,
Bitcoin,-0.13344,0.85765,-10.20778,-5.92060,2.10096,-27.83383
Ethereum,-0.08563,3.87745,-12.89874,2.03260,35.78370,-16.57480
Tether,-0.00201,-0.00122,-0.00928,-0.00944,0.06497,0.09594
USD Coin,-0.01036,-0.00492,-0.01458,-0.00187,-0.02258,-0.02107
BNB,-0.02317,0.48202,-5.57120,12.73835,26.19181,-8.96937
...,...,...,...,...,...,...
BUILD,-1.73847,-3.83740,-13.97361,-19.23929,-19.23929,-19.23929
Super Whale DAO,-0.13180,-1.72533,-3.76127,-1.51986,63.68654,56.03817
Chainsquare,0.45197,0.17291,-1.05837,-0.87773,59.31486,59.31486
Pizza Game,-0.31065,5.79143,-7.95537,57.78223,47.99077,13.39725
PulseDoge,0.20238,6.14559,-6.16760,58.04351,5.41912,-35.01908

In [15]:
#Stacking the results 

df4 = df3.stack()
df4

name
Bitcoin    quote.USD.percent_change_1h     -0.13344
           quote.USD.percent_change_24h     0.85765
           quote.USD.percent_change_7d    -10.20778
           quote.USD.percent_change_30d    -5.92060
           quote.USD.percent_change_60d     2.10096
                                             ...
PulseDoge  quote.USD.percent_change_24h     6.14559
           quote.USD.percent_change_7d     -6.16760
           quote.USD.percent_change_30d    58.04351
           quote.USD.percent_change_60d     5.41912
           quote.USD.percent_change_90d   -35.01908
Length: 29910, dtype: float64

In [16]:
df5 = df4.to_frame(name='values')
df5

                                          values
name
Bitcoin   quote.USD.percent_change_1h   -0.13344
          quote.USD.percent_change_24h   0.85765
          quote.USD.percent_change_7d  -10.20778
          quote.USD.percent_change_30d  -5.92060
          quote.USD.percent_change_60d   2.10096
...                                          ...
PulseDoge quote.USD.percent_change_24h   6.14559
          quote.USD.percent_change_7d   -6.16760
          quote.USD.percent_change_30d  58.04351
          quote.USD.percent_change_60d   5.41912
          quote.USD.percent_change_90d -35.01908

[29910 rows x 1 columns]

In [17]:
df5.count()

values    29910
dtype: int64

In [23]:


index = pd.Index(range(29910))
df6 = df5.reset_index()
df6

            name                       level_1    values
0        Bitcoin   quote.USD.percent_change_1h  -0.13344
1        Bitcoin  quote.USD.percent_change_24h   0.85765
2        Bitcoin   quote.USD.percent_change_7d -10.20778
3        Bitcoin  quote.USD.percent_change_30d  -5.92060
4        Bitcoin  quote.USD.percent_change_60d   2.10096
...          ...                           ...       ...
29905  PulseDoge  quote.USD.percent_change_24h   6.14559
29906  PulseDoge   quote.USD.percent_change_7d  -6.16760
29907  PulseDoge  quote.USD.percent_change_30d  58.04351
29908  PulseDoge  quote.USD.percent_change_60d   5.41912
29909  PulseDoge  quote.USD.percent_change_90d -35.01908

[29910 rows x 3 columns]

In [24]:
# Change the column name

df7 = df6.rename(columns={'level_1': 'percent_change'})
df7

            name                percent_change    values
0        Bitcoin   quote.USD.percent_change_1h  -0.13344
1        Bitcoin  quote.USD.percent_change_24h   0.85765
2        Bitcoin   quote.USD.percent_change_7d -10.20778
3        Bitcoin  quote.USD.percent_change_30d  -5.92060
4        Bitcoin  quote.USD.percent_change_60d   2.10096
...          ...                           ...       ...
29905  PulseDoge  quote.USD.percent_change_24h   6.14559
29906  PulseDoge   quote.USD.percent_change_7d  -6.16760
29907  PulseDoge  quote.USD.percent_change_30d  58.04351
29908  PulseDoge  quote.USD.percent_change_60d   5.41912
29909  PulseDoge  quote.USD.percent_change_90d -35.01908

[29910 rows x 3 columns]

In [26]:
df7['percent_change'] = df7['percent_change'].replace(['quote.USD.percent_change_24h','quote.USD.percent_change_7d','quote.USD.percent_change_30d','quote.USD.percent_change_60d','quote.USD.percent_change_90d'],['24h','7d','30d','60d','90d'])
df7

            name               percent_change    values
0        Bitcoin  quote.USD.percent_change_1h  -0.13344
1        Bitcoin                          24h   0.85765
2        Bitcoin                           7d -10.20778
3        Bitcoin                          30d  -5.92060
4        Bitcoin                          60d   2.10096
...          ...                          ...       ...
29905  PulseDoge                          24h   6.14559
29906  PulseDoge                           7d  -6.16760
29907  PulseDoge                          30d  58.04351
29908  PulseDoge                          60d   5.41912
29909  PulseDoge                          90d -35.01908

[29910 rows x 3 columns]

In [25]:

import seaborn as sns
import matplotlib.pyplot as plt